spring.application.name=backend
spring.profiles.active=jdbc
spring.datasource.url=jdbc:mysql://newsdatabase1.cluster-cdsuisooeg8u.us-east-1.rds.amazonaws.com:3306/news?useSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.internal.news.saving.way=db
#the above can take db or s3

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=m0wn1ka0001@gmail.com
spring.mail.subject=News of today by radha
spring.mail.password=${SMTP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.razorpay.amount=100
spring.razorpay.KEY_ID=REDACTED
spring.razorpay.KEY_SECRET=REDACTED
spring.news.cron.time=0 0 3 * * *
#spring.news.cron.time=0 * * * * *

server.port=8080
server.address=0.0.0.0