spring.application.name=backend
spring.profiles.active=jdbc
spring.datasource.url=jdbc:mysql://localhost:3306/news?useSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.internal.news.saving.way=db
#the above can take db or s3

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=m0wn1ka0001@gmail.com
spring.mail.subject=News of today by radha
spring.mail.password=redacted
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true