spring.application.name=backend
spring.profiles.active=jdbc
spring.datasource.url=jdbc:mysql://localhost:3306/news?useSSL=false&useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
